### ISSUE TITLE
Issues with creating custom Tokenizer

### ISSUE THREAD

**Issue by grindthemall** [teamtnt/tntsearch#182]
I am trying to create a new Tokenizer given I have some very unique requirements for my users (I need to be able to search punctuation like [] and + and -).  

I followed the instructions from issue #21 and ran into some issues.

First my code:
`<?php

require_once __DIR__ . '/vendor/autoload.php';
use TeamTNT\TNTSearch\TNTSearch;
use TeamTNT\TNTSearch\Support\TokenizerInterface;
use TeamTNT\TNTSearch\Indexer\TNTIndexer;

class ATokenizer implements TokenizerInterface {

    public function tokenize($text) {
        return preg_split("[^\p{L}\p{N}\-\+\[\]\(\)\!\@\#\$\%\^\&\*\_\-\{\}\=\.\?\/\\\:\;\"\'\<\>\,\|\~\`]+/u", strtolower($text), -1, PREG_SPLIT_NO_EMPTY);
    }
}

$atokenizer = new ATokenizer;

$tnt = new TNTSearch;
$indexer = new TNTIndexer;

$tnt->loadConfig([
   <removed for security>
    'storage'   => '/search/',
    'stemmer'   => \TeamTNT\TNTSearch\Stemmer\PorterStemmer::class//optional
]);

$indexer->setTokenizer($atokenizer);
$indexer = $tnt->createIndex('posts.index');
$indexer->query('SELECT id, theMessage, refs, qpostNo FROM posts;');
$indexer->run();
?>`

If I run the code above I get the following error:
Fatal error: Declaration of ATokenizer::tokenize($text) must be compatible with TeamTNT\TNTSearch\Support\TokenizerInterface::tokenize($text, $stopwords) in /searchindexer.php on line 13

After reviewing the default tokenizer I updated my custom class to this:
`public function tokenize($text, $stopwords = [])`

and the error went away.

Per the directions given in #21 I should also define $indexer = TNTIndexer.
I had to add the line:
`use TeamTNT\TNTSearch\Indexer\TNTIndexer`
To get the class to load properly.

However, when I try to use the class I get the following error:
Fatal error: Uncaught Error: Call to a member function exec() on null in /vendor/teamtnt/tntsearch/src/Indexer/TNTIndexer.php:56
Stack trace:
#0 /searchindexer.php(31): TeamTNT\TNTSearch\Indexer\TNTIndexer->setTokenizer(Object(ATokenizer))
#1 {main}
  thrown in /vendor/teamtnt/tntsearch/src/Indexer/TNTIndexer.php on line 56

How do I solve this problem so I can use a custom tokenizer?

**Comment by Gu3** [comment]
Hi, 
try  : 
$indexer = $tnt->createIndex('posts.index');
and only after : 
$indexer->setTokenizer($atokenizer);

Index must existe before setting tokenizer.

**Comment by grindthemall** [comment]
Ok updated my code and the index built (looks like its an index of only characters).  Now I get a new error and I cannot seem to figure out where I need to send an array:

Processed 1000 rows
Processed 2000 rows
Processed 3000 rows
Total rows 3868

Fatal error: Uncaught InvalidArgumentException: Passed variable is not an array or object in /home/customer/www/qagg.news/public_html/vendor/teamtnt/tntsearch/src/Support/Collection.php:153
Stack trace:
#0 /vendor/teamtnt/tntsearch/src/Support/Collection.php(153): ArrayIterator->__construct(NULL)
#1 /vendor/teamtnt/tntsearch/src/TNTSearch.php(109): TeamTNT\TNTSearch\Support\Collection->getIterator()
#2 charsearchindexer.php(40): TeamTNT\TNTSearch\TNTSearch->search('[', 100)
#3 {main}
  thrown in /vendor/teamtnt/tntsearch/src/Support/Collection.php on line 153



Code below.

`require_once __DIR__ . '/vendor/autoload.php';
use TeamTNT\TNTSearch\TNTSearch;
use TeamTNT\TNTSearch\Support\TokenizerInterface;
use TeamTNT\TNTSearch\Indexer\TNTIndexer;

class ATokenizer implements TokenizerInterface {

    public function tokenize($text, $stopwords=[]) {
        return preg_split("[^\p{L}\p{N}\-\+\[\]\(\)\!\@\#\$\%\^\&\*\_\-\{\}\=\.\?\/\\\:\;\"\'\<\>\,\|\~\`]+/u", strtolower($text), -1, PREG_SPLIT_NO_EMPTY);
    }
}

$atokenizer = new ATokenizer;

$tnt = new TNTSearch;
$indexer = new TNTIndexer;

$tnt->loadConfig([
    'driver'    => 'mysql',
    'host'      => '127.0.0.1',
    'database'  => '<removed>',
    'username'  => '<removed>',
    'password'  => '<removed>',
    'storage'   => './tntsearch/',
    'stemmer'   => \TeamTNT\TNTSearch\Stemmer\PorterStemmer::class
]);


//$indexer->setTokenizer($atokenizer);
$indexer = $tnt->createIndex('chars.index');
$indexer->setTokenizer($atokenizer);
$indexer->query('SELECT id, theMessage, qpostNo FROM posts;');
$indexer->run();

$tnt->selectIndex("chars.index");
$tnt->fuzziness = true;

$res = $tnt->search("[",100);

print_r($res);`

**Comment by Gu3** [comment]
hum...
Try to dump your keywords value here : https://github.com/teamtnt/tntsearch/blob/master/src/TNTSearch.php#L97
Your tokenizer need to return an array.
