### ISSUE TITLE
error when using search method

### ISSUE THREAD

**Issue by the94air** [teamtnt/tntsearch#64]
The error
```
Fatal error: Uncaught Error: Call to a member function stem() on null in C:\xampp\htdocs\vendor\teamtnt\tntsearch\src\TNTSearch.php:79 Stack trace: #0 [internal function]: TeamTNT\TNTSearch\TNTSearch->TeamTNT\TNTSearch\{closure}('this', 0) #1 C:\xampp\htdocs\vendor\teamtnt\tntsearch\src\Support\Collection.php(56): array_map(Object(Closure), Array, Array) #2 C:\xampp\htdocs\vendor\teamtnt\tntsearch\src\TNTSearch.php(80): TeamTNT\TNTSearch\Support\Collection->map(Object(Closure)) #3 C:\xampp\htdocs\index.php(23): TeamTNT\TNTSearch\TNTSearch->search('This is a test ...', 12) #4 {main} thrown in C:\xampp\htdocs\vendor\teamtnt\tntsearch\src\TNTSearch.php on line 79
```
My code
```
<?php

require 'vendor/autoload.php';

use TeamTNT\TNTSearch\TNTSearch;

$tnt = new TNTSearch;

$tnt->loadConfig([
    'driver'    => 'mysql',
    'host'      => 'localhost',
    'database'  => 'search',
    'username'  => 'root',
    'password'  => '',
    'storage'   => 'C:/xampp/htdocs/tntsearch'
]);

$indexer = $tnt->createIndex('name.index');
$indexer->query('SELECT id, name, article, slug FROM articles;');
//$indexer->setLanguage('german');
$indexer->run();

$res = $tnt->search("This is a test search", 12);

print_r($res);

**Comment by the94air** [comment]
Oops. just a bad call
